spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hafida1998/configCentral.git
      uri: http://localhost:8888
      fail-fast: true

server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
